### ISSUE TITLE
Create separate message objects for NtC and NtN for handshake mini-protocol

### ISSUE THREAD

**Issue by agaffney** [blinklabs-io/gouroboros#103]
The format of the version data is different between NtN and NtC. The code currently uses `interface{}` for this field in the propose/accept messages, but we need a better way to get at the data in it.

For reference, the NtC version data is:

```
nodeToClientVersionData = networkMagic
```

and the NtN version data is:

```
nodeToNodeVersionData = [ networkMagic , initiatorAndResponderDiffusionMode ]
```

**Comment by wolf31o2** [comment]
This no longer seems to be the case. It looks like we resolved this along the way.
