### ISSUE TITLE
chainsync GetCurrentTip is not clearing intersectResultChan 

### ISSUE THREAD

**Issue by safanaj** [blinklabs-io/gouroboros#253]
GetCurrrentTip is not clearing the error channel that is always used on intersect handlers, [here](https://github.com/blinklabs-io/gouroboros/blob/2281362fd3a9199ace68fff14e45845b54a79dd0/protocol/chainsync/client.go#L321) , this cause a successive call to Sync to block forever.

It should clear it as the GetAvailableBlockRange is doing [here](https://github.com/blinklabs-io/gouroboros/blob/2281362fd3a9199ace68fff14e45845b54a79dd0/protocol/chainsync/client.go#L143)

**Comment by agaffney** [comment]
Thank you @safanaj for the bug report and suggested fix
