### ISSUE TITLE
chainsync StopSyncProcessError cause handlers to block on readyForNextBlockChan

### ISSUE THREAD

**Issue by safanaj** [blinklabs-io/gouroboros#254]
On RollBackward and RollForward handlers, the readyForNextBlockChan is filled when a StopSyncProcessError is catched from the callback, 2 messages are sent to the readyForNextBlockChan. This can cause leaks as the handler could block forever.

Calling 2 subsequent Sync that stops the loop on the first received message , the callback handler of the second call is blocked/never called.
Example code to reproduce:
```
func main() {
	ctx := context.Background()
	address := "bart.bardels.me:6001"
	conn, err := (&net.Dialer{Timeout: time.Second}).DialContext(ctx, "tcp", address)
	if err != nil {
		panic(err)
	}

	o, _ := ouroboros.New(
		ouroboros.WithConnection(conn),
		ouroboros.WithNetwork(ouroboros.NetworkByName("mainnet")),
		ouroboros.WithNodeToNode(true),
		ouroboros.WithKeepAlive(true),
		ouroboros.WithChainSyncConfig(chainsync.NewConfig(
			chainsync.WithBlockTimeout(30*time.Second),
			chainsync.WithRollBackwardFunc(func(p common.Point, t chainsync.Tip) error {
				fmt.Printf("chainsync.RollBackwardFunc: point: %+v -- tip: %+v\n", p, t)
				return chainsync.StopSyncProcessError
			}),
			chainsync.WithRollForwardFunc(func(n uint, x interface{}, t chainsync.Tip) error {
				fmt.Printf("chainsync.RollForwardFunc: uint: %v -- x: %T -- tip: %+v\n", n, x, t)
				return chainsync.StopSyncProcessError
			}),
		)),
	)
	o.ChainSync().Client.Start()

	sp := common.NewPoint(
		92277900,
		func() []byte {
			b, _ := hex.DecodeString("6bf0ed7fd582d78433e1b1863da8d545fdb465d115dc353ccdbd0120f8509c90")
			return b
		}(),
	)

	err = o.ChainSync().Client.Sync([]common.Point{sp})
	if err != nil {
		o.Close()
		panic(err)
	}
	err = o.ChainSync().Client.Sync([]common.Point{sp})
	if err != nil {
		o.Close()
		panic(err)
	}
	select {}
}
```
The message is not printed on the second Sync call.

[here](https://github.com/blinklabs-io/gouroboros/blob/2281362fd3a9199ace68fff14e45845b54a79dd0/protocol/chainsync/client.go#L290) and [here](https://github.com/blinklabs-io/gouroboros/blob/2281362fd3a9199ace68fff14e45845b54a79dd0/protocol/chainsync/client.go#L310) the readyForNextBlockChan is filled and the handlers are filling it again just before to return, my guess is that after signaling the syncLoop to giveup the handlers should return nil.

**Comment by agaffney** [comment]
Thank you @safanaj for the bug report and suggested fix
