### ISSUE TITLE
Protocol parameters query response changed in node v8.0.0

### ISSUE THREAD

**Issue by wolf31o2** [blinklabs-io/gouroboros#274]
The new cardano-node v8.0.0 changes the on wire protocol response object for the protocol parameters local state query.

More info: CardanoSolutions/ogmios#314

**Comment by AndrewWestberg** [comment]
Sounds like they're working on a fix in 8.1.0. Probably better to just wait on the fix in the node instead of implementing any work-arounds. That's the approach I'm going to take for now.
